### ISSUE TITLE
Make external syntax easier to read

### ISSUE THREAD

**Issue by mathvav** [ShearOfDoom/Cactus#18]
We currently require a ton of nesting to make stuff somewhat readable

Even a simple "map" is really hard to read:

``` python
GAME_MAP = GameMap([
    MapPosition(
        "Start",
        "Welcome to the start!",
        "Now leaving the start.",
        {
            "left": 1,
            "right": 2,
        },
    ),
    MapPosition(
        "Left",
        "You took the left path and died.",
        "",
        {},
        function=exit,
    ),
    MapPosition(
        "Right",
        "You took the right path and lived!",
        "",
        {},
        function=exit,
    ),
])
```

How can we fix this? I was thinking about making everything more paramaterized. i.e. we would do this:

``` python
game_map = GameMap("someBasicStuff")

game_map.add_location("Left", "You took the left path and died", "", {}, otherData)
```

Any other suggestions to make it easier to use?

**Comment by Ethan-Bierlein** [comment]
This ide will be implemented. The original syntax will remain as an option though as well. _(If I forget to do this, just ---bop me on the head--- remind me about it.)_

**Comment by mathvav** [comment]
Aren't those required arguments?

Yes, you're right that we have to make it editable later, but I think we should make the syntax easy to read and edit in the first place so there's no confusion and it's easy to use

**Comment by Ethan-Bierlein** [comment]
Hmm, here's an idea. We could encourage users to use `MyInstance(myparam=value)` when declaring instances, rather than just `MyInstance(value)`. It's not something that's enforceable, but it would make reading stuff easier.

**Comment by mathvav** [comment]
Interesting idea, but we still have a mess of tangled-up code

**Comment by mathvav** [comment]
And that's a _lot_ more writing

**Comment by Ethan-Bierlein** [comment]
I certainly think an `add_location` function will help slightly, also using dictionary keys as references, like I said in the other issue, will probably help.

**Comment by mathvav** [comment]
The biggest issue with an `add_location` function is that validation won't work right if it depends on a function not there yet. And **never** trust the user to validate themselves :grin:

Hmm... I have another idea:

Why don't we just use a dictionary? They can do stuff like

``` python
MyInstance({
    "name": "My Name"
    "welcome_text": "Welcome to my game!"
})
```

Forced labels, easy (easier) to edit, can have many optional fields that aren't possible with a function, etc.

We could then validate on changes.

Wouldn't copy each value into a variable, instead, we would do `self.data["name"]`

We'll have to have a graceful exception handling system for this so it doesn't spew out a bunch of stuff at the user.

**Comment by Ethan-Bierlein** [comment]
Alrighty. I think that sounds like a plan. We're going to use a dictionary to store data in all the classes, `GameMap` and `MainGame` included. I'm going to close this issue now, if nobody minds.

**Comment by mathvav** [comment]
Don't you just _love_ breaking changes? :D 

**Don't close** until it is fixed (with a commit and a PR)
