### ISSUE TITLE
Using dictionary keys as MapPosition references rather than indexes

### ISSUE THREAD

**Issue by Ethan-Bierlein** [ShearOfDoom/Cactus#19]
While the current system isn't too hard, it'd be easier for larger projects if we could use dictionary keys as references rather than indexes, like so:

```
{
    "choice1": "mykey",
    ...
}
```

**Comment by mathvav** [comment]
We'll also have to update the validator for this change

**Comment by mathvav** [comment]
Also: add an alias for `same_room` (or similar)
