### ISSUE TITLE
Coding Convention

### ISSUE THREAD

**Issue by mathvav** [ShearOfDoom/Cactus#2]
Can we please establish a coding convention?

**[PEP 8](https://www.python.org/dev/peps/pep-0008/)** seems to be the prevalent style in the Python ecosystem, but we don't seem to conform with class definitions.

All established open source projects have a coding convention, so we should also.

**Comment by Ethan-Bierlein** [comment]
Hmm. The only non-pep8 thing I see is extra spaces around `=`, but that's usually part of my convention, simply because it looks better. I'm not sure what's meant by the class names not being right.

**Comment by mathvav** [comment]
> Always use cls for the first argument to class methods.

I was saying to make it a part of the readme so we can follow it. Hmm....

**Comment by mathvav** [comment]
Those are two separate thoughts BTW ^^^

**Comment by Ethan-Bierlein** [comment]
Really? Hmm. I would've thought that'd you'd use `self`, as in referring to the object itself...

**Comment by mathvav** [comment]
I don't know. It also says this:

> Always use self for the first argument to instance methods.
