### ISSUE TITLE
Are we going to do docs on the wiki or on pages?

### ISSUE THREAD

**Issue by mathvav** [ShearOfDoom/Cactus#31]
If on pages, we should disable the wiki here (to avoid confusion)

**Comment by Ethan-Bierlein** [comment]
We're doing docs on the Github wiki, here. I'm not sure what you mean by "pages". Are you talking about the website?

**Comment by Ethan-Bierlein** [comment]
Welp. I guess we have this setteled anyways, so I'm closing it.

**Comment by mathvav** [comment]
Yes, the website. Docs are often done in GitHub pages because it can render Markdown. It's looks nicer vs. doesn't require a pull request to edit. Personally, I like pages better, but I don't know what we want.

Wikis are older

**Comment by Ethan-Bierlein** [comment]
Hmm. Okay. I'll see what I can do about the current docs.

**Comment by mathvav** [comment]
We don't have any currently, silly :D

**Comment by Ethan-Bierlein** [comment]
Yeah we do. Go to the Wiki tab on the repo.

**Comment by mathvav** [comment]
I can migrate everything if we want docs. Leave the technical stuff up to me; just tell me what you want.

**Comment by Ethan-Bierlein** [comment]
Okay, so the current pages on our repo's wiki, let's migrate them to the website, and then any other wiki pages I add, we can just migrate.

**Comment by mathvav** [comment]
Don't add any more there. I'll work on documentation now.

Also, can we get a styleguide for Markdown? I have one that I like and the output always looks good. I'll put it online for you to peek at.

**Comment by Ethan-Bierlein** [comment]
Alright, you can use your md style.
