### ISSUE TITLE
Global commands

### ISSUE THREAD

**Issue by mathvav** [ShearOfDoom/Cactus#34]
We should have the option for a user to add global commands, like `quit`.

We should have them integrated into the "fabric mesh," so a user can have one for going to a saved home, or to an inventory/other menu.

As usual, they should be able to bind to these commands.

**Comment by Ethan-Bierlein** [comment]
I'm going to assign myself to this. That sound good?

**Comment by mathvav** [comment]
Sure. Can you please run the PR past me to make sure that all of the binding code isn't broken by this? It's easier just for me to check than for me to explain

**Comment by Ethan-Bierlein** [comment]
I don't have a commit yet, but I'll put up the PR as soon as I have it.

**Comment by mathvav** [comment]
Make sure to add these global commands to the `help` command, at the very beginning (the same time as it says the notes about `about` and `help`), and add a `game.command.XXX` to the event listener
