### ISSUE TITLE
Correctly set leading underscore for class members

### ISSUE THREAD

**Issue by mathvav** [ShearOfDoom/Cactus#40]
General Convention:
- Leading underscore indicates that you shouldn't mess with this item in this class (equivalent of private)
- No leading underscore says that it's [somewhat] safe to mess with

**Comment by mathvav** [comment]
@Ethan do we want leading underscores for _everything_ that the user can use safely or only what is relevant? Like, do we want a leading underscore on `find_start()` in `GameMap`?

**Comment by Ethan-Bierlein** [comment]
I think we'll put leading underscores for anything that shouldn't be directly run/changed.
