### ISSUE TITLE
How should we handle exceptions?

### ISSUE THREAD

**Issue by mathvav** [ShearOfDoom/Cactus#41]
Exceptions happen in code. Often.

We don't want to spew this data at the user's face, so exceptions would be a good idea.

Having a unified exception "type" would be good for this so the user can catch these (I'm not sure much about Python exceptions)

Should we also log exceptions to a file? Tell the user that something bad happened internally? What?

**Comment by Ethan-Bierlein** [comment]
Hmm. Maybe we could have a private `cactus_errors` file with error classes.

**Comment by mathvav** [comment]
Hmm.... what would those error classes do?

**Comment by Ethan-Bierlein** [comment]
We'd raise those errors.

**Comment by mathvav** [comment]
Oh I see.

Do you also want to do logging and/or user input?

The use for these functions would be for validation purposes mostly

**Comment by mathvav** [comment]
Suggestion:
1. We throw an exception that could be caught by the gamemaker
2. We create a log file somewhere with a timestamp, error message, and the list of previous command used (to replicate error)
3. We alert the user that the game reached an error **by the developer** and what they should give the dev when reporting this

Optional: we require an email to show to the user when an error occurs.

I don't like alerting the user for a catchable exception (it seems pointless to have an exception in the first place here), but I doubt that many would properly catch that exception

**Comment by mathvav** [comment]
Note to whoever fixes this: make sure to change the ValueError in _check_possible_choices or whatever that method is called

**Comment by mathvav** [comment]
One place we need an exception is in the find function in `CactusName`; it returns `-1` if not found, but this really should throw an exception

**Comment by Ethan-Bierlein** [comment]
Issue fixed. The only thing you have to do is put the `@cactus_class_method_exception_handle` decorator over each classmethod.
