### ISSUE TITLE
Implement colorama

### ISSUE THREAD

**Issue by mathvav** [ShearOfDoom/Cactus#42]
https://pypi.python.org/pypi/colorama

To make everything streamlined for the user, we should also define all of the colors ourself... somehow. Whoever can find a way to do a syntax like `Backgroud_Color.Red` please take this issue.

I don't want the user to have to deal with colorama itself because it's not as streamlined. I want _everything_ the user needs to be in Cactus itself

**Comment by mathvav** [comment]
@ShearOfDoom why is this [wontfix]?

**Comment by Ethan-Bierlein** [comment]
@Annonomus-Penguin I attempted an implementation, but it failed miserably. You can try if you want to.
