### ISSUE TITLE
pyfiglet support

### ISSUE THREAD

**Issue by mathvav** [ShearOfDoom/Cactus#43]
Add support for https://github.com/pwaller/pyfiglet or other programs like it.

Like I said earlier, everything that the user needs for a good game should be cactus itself.

**Comment by Ethan-Bierlein** [comment]
Okay. I've already got some stuff here in issues that I'm working on, so I'm assuming you can take this.

**Comment by mathvav** [comment]
I just thought of this right now and thought that this would be a good thing to add sometime in the future.

I'm trying to add stuff for people to do if they want to join the project (so we don't shrug our shoulders and waste help)

**Comment by Ethan-Bierlein** [comment]
Yup. I know. I think it's a good idea, I'll just let you implement it.

**Comment by mathvav** [comment]
GPL license :sob:, so we can't do this.
