### ISSUE TITLE
Rename classes

### ISSUE THREAD

**Issue by mathvav** [ShearOfDoom/Cactus#44]
`MainGame` → `CactusGame`
`MapPosition` → `CactusPosition`
`GameMap` → `CactusMap`

Is this okay @ShearOfDoom?

**Comment by Ethan-Bierlein** [comment]
Do it :)

**Comment by mathvav** [comment]
Later :D

**Comment by Ethan-Bierlein** [comment]
Oh, and when renaming classes, can you rename the class instances in `test.py`?

**Comment by mathvav** [comment]
Will do
