### ISSUE TITLE
Validate class_data

### ISSUE THREAD

**Issue by mathvav** [ShearOfDoom/Cactus#45]
We need to validate `class_data` in all three classes:
- During `__init__`
- Every time it's changed

We need to make sure:
- Everything that's required is there
- Nothing extra is there
- All of the items are of the correct types (key and value)

The first one is easy to do, but how do we do the second one, especially when data could change mid-function? Too bad we couldn't "watch" the dictionary for any changes.

This is the reason why I wanted the `__init__` argument to be a dictionary, but it actually stored as the actual variables

**Comment by Ethan-Bierlein** [comment]
I can do this, unless you want to.

**Comment by mathvav** [comment]
How are you going to do it every time it's changed?

**Comment by Ethan-Bierlein** [comment]
Well, I'm assuming there would be an `add_position` function for a `CactusMap`, so, before it's added, validate it.

**Comment by mathvav** [comment]
But that doesn't solve the issue.

I could externally edit the dictionary and it would be unvalidated

**Comment by Ethan-Bierlein** [comment]
Prefix `class_data` with an underscore. That way only `add_position` can modify it.

**Comment by mathvav** [comment]
Ok, but we still can't edit any of the other items.

So we need to prefix it with an underscore no matter what.

Do we want specific stuff like set name and get name? Or a generic set_attribute("key", value) function?

**Comment by Ethan-Bierlein** [comment]
A generic `set_attribute` function wouldn't be the greatest because certain values have to have certain types, and it's not appending or anything, it's completely resetting the value.

**Comment by mathvav** [comment]
We could have it do set(append(stuff, get())) but that's not the best.

**Comment by mathvav** [comment]
We also need to call evaluate choices for validation when the map changes

**Comment by mathvav** [comment]
1. An idea: we could validate this every time `_handle_event()` is called.
2. I still don't think that we should be storing this stuff internally in a dictionary (from readability and validation purposes)... why do you what to do this in the first place? What advantage does this offer?
