### ISSUE TITLE
Rename `CactusSource` to `cactus`; remove prefix (sorry!)

### ISSUE THREAD

**Issue by mathvav** [ShearOfDoom/Cactus#50]
This would allow the user, once they set the `PYTHONPATH`, to do this:

``` python
import cactus.game
import cactus.map
import cactus.position

my_game = cactus.Game(data)
```

Then, we could also do stuff like this later:

``` python
import cactus.color

print(cactus.color.red + "This is red!")
```

**Comment by Ethan-Bierlein** [comment]
Can you name it to `Cactus` with a capital C? Thanks.

**Comment by Ethan-Bierlein** [comment]
Also, don't use `map` as a file name. Can you just use `game_map`? I don't want any possibility of name conflicts.

**Comment by mathvav** [comment]
Cactus has to be lowercase according to PEP 8.

This is convention:

``` python
import sys
```

**Comment by Ethan-Bierlein** [comment]
And `position` to `map_position`.

**Comment by mathvav** [comment]
Both of those won't have conflicts because the user will use them as `cactus.Map()` and `cactus.Position()`

**Comment by Ethan-Bierlein** [comment]
No, I think they'd have to do `cactus.position.Position()`, not just `cactus.Position()`.

**Comment by Ethan-Bierlein** [comment]
Okay, how about this. 
- Rename `CactusSource` to `Cactus`, or `cactus`.
- Keep the same name for the file `game_map`.
- Keep the same name for the file `map_position`.

**Comment by mathvav** [comment]
You're right about `cactus.position.Position()`. I just tested it.

Okay:
- Rename to `cactus`
- I don't want `cactus.cactus_position.CactusPosition()`
- I don't want `cactus.cactus_map.CactusMap()`

**Comment by Ethan-Bierlein** [comment]
So, in short, we should do this.
- Rename `CactusSource` to `cactus`.
- Rename the file `cactus_position` to `position`.
- Rename the file `cactus_map` to `game_map`.
- Rename the file `cactus_game` to `game`.

**Comment by Annonomus-Penguin** [comment]
How about this?:

 - Rename to `cactus` (lower C)
 - Rename to `cactus.flowchart.Flowchart()`
 - Rename to `cactus.position.Position()`
 - Set the `__init__.py` file to this:
    
    ```python
    
    
    ```

Now the user could do this:

```python
import cactus

my_game = cactus.
```

**Comment by ShearOfDoom** [comment]
Wait, `cactus.flowchart.Flowchart()`? When was that implemented?

**Comment by mathvav** [comment]
How about this?:
- Rename to `cactus` (lower C)
- Rename to `cactus.flowchart.Flowchart()` (I don't want to have to do `cactus_map`, so I think we should start calling it a flowchart, as that's what it really is)
- Rename to `cactus.position.Position()`
- Rename to `cactus.game.Game()`
- Set the `__init__.py` file to this:
  
  ``` python
  from game import Game
  from flowchart import Flowchart
  from position import Position
  ```

Now the user could do this:

``` python
import cactus

my_game = cactus.Game(data)
```

For "optional components" (like `cactus.color`), they wouldn't have to include them.

**Comment by Ethan-Bierlein** [comment]
Alrighty. Go ahead! :)

**Comment by mathvav** [comment]
OK, do you have any local changes or can I ---wreck--- edit the repo right now? This'll take ~10-15 minutes to make sure everything's right

**Comment by Ethan-Bierlein** [comment]
Nope. No local changes rn.
