### ISSUE TITLE
Game map validator

### ISSUE THREAD

**Issue by mathvav** [ShearOfDoom/Cactus#6]
We need to make sure that the links between the rooms are valid.

We should validate the user's input in `MainGame.__init__()`.

**Comment by Ethan-Bierlein** [comment]
This is a good idea. Although, generally, it's not the greatest idea to put code other than attribute declarations inside `__init__`. I'd probably implement this as a separate function, and have it be run when `play_game()` is called.

**Comment by mathvav** [comment]
Hmm... it would also have to be re-validated if the user ever changes the data

We might need to make the data "private" (indicate not to use it with a leading underscore) and then have a `get_data()` function and a `set_data()` function that automatically validates.

**Comment by Ethan-Bierlein** [comment]
Fixed this. Going to close.
