### ISSUE TITLE
Use functions rather than Strings for enter and exit events

### ISSUE THREAD

**Issue by nic-hartley** [ShearOfDoom/Cactus#7]
This lets rooms be dynamic -- for example, you could enter a room, knock a torch down, and the room catches on fire. If you try to enter the room again, it could deduct (for example) four health and tell you:

```
HOLY CRAP YOU'RE ON FIRE AAGAHGASKGHASG
```

**Comment by mathvav** [comment]
Look at #5 

We could have an `onRoomEnter` event, possibly?

**Comment by nic-hartley** [comment]
...Dammit, you posted an issue about it before I could.
